### ISSUE TITLE
Minimum stable version not defined

### ISSUE THREAD

**Issue by tambolishahid** [fuguevit/repository#10]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package fuguevit/repository could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by fuguevit** [comment]
Thanks, I will check it soon.

**Comment by fuguevit** [comment]
An embarrassing mistake, I changed the package name but forgot update README file.
Updated, using `composer require fuguevit/repositories`

Thanks @tambolishahid

**Comment by tambolishahid** [comment]
@fuguevit welcome
